### ISSUE TITLE
Problema no DataStudio - Código do erro: 7f9cfd9b

### ISSUE THREAD

**Issue by conradogrecco** [Gladior-B-V/google-my-business-connector#2]
Código do erro: 7f9cfd9b

**Comment by zoedufrenne** [comment]
Hi @conradogrecco ,
When do you get this message? 
Is it when you start connection to Looker Stuio or is it an already existing dashboard that got this message?

**Comment by conradogrecco** [comment]
Hi! The panel was working normally, but yesterday it simply lost data connection, showing the error; Unknown Error - There was an error communicating with the service.

 

Error code: 7ec1c8f1

 

 

De: zoedufrenne ***@***.***> 
Enviada em: quinta-feira, 8 de dezembro de 2022 11:46
Para: Gladior-B-V/google-my-business-connector ***@***.***>
Cc: conradogrecco ***@***.***>; Mention ***@***.***>
Assunto: Re: [Gladior-B-V/google-my-business-connector] Problema no DataStudio - Código do erro: 7f9cfd9b (Issue #2)

 

Hi @conradogrecco <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fconradogrecco&data=05%7C01%7C%7Ca3faf25ebf894b44029108dad92ae56e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638061075524270062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9xrCvrvVAifFInAOcGQK4BA0LMeh8K5iT4buQm%2BTEsY%3D&reserved=0>  ,
When do you get this message?
Is it when you start connection to Looker Stuio or is it an already existing dashboard that got this message?

**Comment by conradogrecco** [comment]
Não aparece as contas, mesmo as empresas estando com a localização correta.

 

De: zoedufrenne ***@***.***> 
Enviada em: quinta-feira, 8 de dezembro de 2022 11:46
Para: Gladior-B-V/google-my-business-connector ***@***.***>
Cc: conradogrecco ***@***.***>; Mention ***@***.***>
Assunto: Re: [Gladior-B-V/google-my-business-connector] Problema no DataStudio - Código do erro: 7f9cfd9b (Issue #2)

 

Hi @conradogrecco <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fconradogrecco&data=05%7C01%7C%7Ca3faf25ebf894b44029108dad92ae56e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638061075524270062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9xrCvrvVAifFInAOcGQK4BA0LMeh8K5iT4buQm%2BTEsY%3D&reserved=0>  ,
When do you get this message?
Is it when you start connection to Looker Stuio or is it an already existing dashboard that got this message?

**Comment by zoedufrenne** [comment]
Hi, is it possible to share your dashboard with us and let us know with which emailadress you've made the connection? 
You can share it with, data-dashboards@gladior.com. I will check with development why you are getting the error.
