### ISSUE TITLE
GMB connector Issue

### ISSUE THREAD

**Issue by gpo-analtics** [Gladior-B-V/google-my-business-connector#4]
![image](https://github.com/Gladior-B-V/google-my-business-connector/assets/143100340/ecd14f23-f921-4ef3-8f08-55b9d1189923)

I am getting this Community ConnectorError when trying to set up my GMB connection. Also, we have about 6 different accounts  with up to 2.5K locations in a single account. Will this free connector work or do I need to upgrade to a paid option?

**Comment by zoedufrenne** [comment]
@gpo-analtics thanks for your message, do you still get this message after reconnecting your credentials to the Data Hub? It's should work, but we didn't test it for so much locations in one account. We have a paid version for Google Business Profile. With the paid version you can connect multiple locations in one connection directly to your Looker Studio Dashboard.
