### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by Hypnotoasted** [Gladior-B-V/google-my-business-connector#5]
Upon logging into my Looker account today to look at my Google Business Profile insights, all my data is running into errors:

> **A System Error**

> Looker Studio has encountered a system error

> Sorry, we encountered an error and were unable to complete your request

Is there a fix for this or this a new issue that has occurred? 

Thank you!

![GBP Connector Issues](https://github.com/Gladior-B-V/google-my-business-connector/assets/140554665/145fd679-6b37-4896-b6e1-602d8aa8c0a8)

**Comment by rkooiker** [comment]
Hi @Hypnotoasted have you tried to revoke access to the credential, and reconnect again? If that does not work, can you share the dashboard with service@gladior.com, and leave your Data Hub account id (this is the number shown on edit profile, should look something like: 80d7c2a3-e36b-4g98-1f35-5421ebb41edc) or email address as a comment on this issue?
