### ISSUE TITLE
Is there a limit to the number of reviews that are pulled by the connector?

### ISSUE THREAD

**Issue by travmp** [Gladior-B-V/google-my-business-connector#6]
I'm uncertain if this issue relates to the GMB connector or the Data Hub. Currently, I'm using the Data Hub to connect to several GMB pages, aiming to create a report that breaks down the ratings and reviews our various locations receive.

My goal is to perform a year-over-year comparison of these reviews and ratings, allowing branches to track their improvement over time. However, it seems that the connection only retrieves the most recent 50 reviews. I haven't found any documentation indicating a 50-review limit or any way to adjust this setting.

I wanted to bring this up in case it helps others encountering the same issue. Thanks!

Here is a link to the report I'm working on: 
https://lookerstudio.google.com/reporting/70a2deb8-3d68-4ec4-b731-339af211e2ce

**Comment by rkooiker** [comment]
Hi @travmp,

There is indeed a limit of 50 reviews. We believe that this is enough for most use cases, and do not want to spend too much resources on retrieving the reviews, as that would increase our cost, which means that we wouldn't be able to give away the Data Hub for free. Your use case does sound very interesting though, and you already have a good looking dashboard! You can contact us at service@gladior.com to inquire about potential paid options for increasing the limit of reviews, and support in other ways in case you run into more issues.

**Comment by travmp** [comment]
Awesome. That sounds good. I thought that might be the case. 

I'll reach out! Thanks for the update
